#!/bin/bash

# Download and untar a 64bit ffmpeg binary.
cd $OPENSHIFT_BUILD_DEPENDENCIES_DIR
if ! (ls | grep ffmpeg); then
  wget http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.latest.tar.gz
  tar xvf ffmpeg.static.64bit.latest.tar.gz
  rm ffmpeg.static.64bit.latest.tar.gz
fi

# install bottle for routing and templates
pip install bottle